name: Deploy VitePress site to Pages

on:
  push:
    branches: [main]  # 将 master 修改为 main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 如果未启用 lastUpdated，则不需要
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.12  # 使用指定版本的 pnpm

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # 使用 Node.js 18
          
      - name: Install dependencies
        run: pnpm install  # 安装项目依赖

      - name: Build with VitePress
        run: |
          pnpm run docs:build  # 启动构建
          touch .nojekyll  # 告诉 GitHub Pages 不用 Jekyll 处理

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1  # 使用 v1 版本，避免废弃
        with:
          path: .vitepress/dist  # 指向构建目录

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}  # 获取部署页面 URL
    needs: build  # 确保在 build 完成后执行部署
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2  # 使用 GitHub Pages 部署动作
